[package]
name = "l-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "*"
cranelift = "0.118.0"
cranelift-module = "0.118.0"
cranelift-jit = "0.118.0"
cranelift-native = "0.118.0"
serde-lexpr = "0.1.3"
serde_derive = "1.0.219"
